sonar.projectKey=phoenix8875_movie_recomendation
sonar.organization=phoenix8875
# only scan the backend source; skip tests/data from analysis
sonar.sources=backend/app
sonar.tests=backend/tests
sonar.python.version=3.12
